# Base URL
BASE_URL = "https://www.sports-reference.com/cbb"

# Year
YEAR = 2019

# Schools
SCHOOLS = [
    # EAST
    "north-carolina-central",
    "north-dakota-state",  # Play in teams
    "belmont",
    "temple",  # Play in teams
    "duke",
    "virginia-commonwealth",
    "central-florida",
    "mississippi-state",
    "liberty",
    "virginia-tech",
    "saint-louis",
    "maryland",
    "louisiana-state",
    "yale",
    "louisville",
    "minnesota",
    "michigan-state",
    "bradley",

    # WEST
    "fairleigh-dickinson",
    "prairie-view",  # Play in teams
    "arizona-state",
    "st-johns-ny",  # Play in teams
    "gonzaga",
    "syracuse",
    "baylor",
    "marquette",
    "murray-state",
    "florida-state",
    "vermont",
    "buffalo",
    "texas-tech",
    "northern-kentucky",
    "nevada",
    "florida",
    "michigan",
    "montana",

    # SOUTH
    "virginia",
    "gardner-webb",
    "mississippi",
    "oklahoma",
    "wisconsin",
    "oregon",
    "kansas-state",
    "california-irvine",
    "villanova",
    "saint-marys-ca",
    "purdue",
    "old-dominion",
    "cincinnati",
    "iowa",
    "tennessee",
    "colgate",

    # MIDWEST
    "north-carolina",
    "iona",
    "utah-state",
    "washington",
    "auburn",
    "new-mexico-state",
    "kansas",
    "northeastern",
    "iowa-state",
    "ohio-state",
    "houston",
    "georgia-state",
    "wofford",
    "seton-hall",
    "kentucky",
    "abilene-christian",
    
    # TEAMS IN SCHEDULES
    "ipfw",
    "arkansas-little-rock",
    "nebraska-omaha",
    "sam-houston-state",
    "citadel",
    "texas-state",
    "south-alabama",
    "niagara",
    "elon",
    "american",
    "siena",
    "texas-am-corpus-christi",
    "western-carolina",
    "missouri-kansas-city",
    "rice",
    "charlotte",
    "florida-international",
    "james-madison",
    "fairfield",
    "utah-valley",
    "quinnipiac",
    "cal-poly",
    "california-riverside",
    "hawaii",
    "california-davis",
    "southern-mississippi",
    "houston-baptist",
    "north-texas",
    "texas-san-antonio",
    "longwood",
    "high-point",
    "campbell",
    "south-carolina-upstate",
    "north-carolina-wilmington",
    "william-mary",
    "montana-state",
    "weber-state",
    "idaho",
    "portland-state",
    "sacramento-state",
    "southern-utah",
    "northern-arizona",
    "chattanooga",
    "mercer",
    "wyoming",
    "nevada-las-vegas",
    "colorado-state",
    "air-force",
    "boise-state",
    "fresno-state",
    "san-jose-state",
    "grand-canyon",
    "california-baptist",
    "youngstown-state",
    "cleveland-state",
    "manhattan",
    "north-carolina-asheville",
    "northwestern-state",
    "northern-colorado",
    "ohio",
    "akron",
    "central-michigan",
    "western-michigan",
    "toledo",
    "milwaukee",
    "marist",
    "massachusetts-lowell",
    "stony-brook",
    "binghamton",
    "new-hampshire",
    "maine",
    "bucknell",
    "boston-university",
    "alabama-birmingham",
    "canisius",
    "texas-el-paso",
    "charleston-southern",
    "presbyterian",
    "maryland-baltimore-county",
    "west-virginia",
    "texas-christian",
    "new-orleans",
    "stephen-f-austin",
    "pepperdine",
    "san-diego",
    "portland",
    "loyola-marymount",
    "san-francisco",
    "pacific",
    "cal-state-bakersfield",
    "texas-arlington",
    "idaho-state",
    "xavier",
    "creighton",
    "depaul",
    "washington-state",
    "arizona",
    "southern-california",
    "stanford",
    "colorado",
    "alabama-am",
    "arkansas-pine-bluff",
    "mississippi-valley-state",
    "jackson-state",
    "texas-southern",
    "winthrop",
    "seattle",
    "louisiana-lafayette",
    "lamar",
    "texas-pan-american",
    "sacred-heart",
    "st-francis-ny",
    "long-island-university",
    "wagner",
    "saint-peters",
    "holy-cross",
    "providence",
    "lafayette",
    "evansville",
    "valparaiso",
    "indiana-state",
    "northern-iowa",
    "new-mexico",
    "iupui",
    "chicago-state",
    "illinois-chicago",
    "northern-illinois",
    "oakland",
    "arkansas-state",
    "santa-clara",
    "utah",
    "robert-morris",
    "cornell",
    "columbia",
    "dartmouth",
    "harvard",
    "brown",
    "cal-state-northridge",
    "monmouth",
    "albany-ny",
    "lehigh",
    "bryant",
    "louisiana-monroe",
    "furman",
    "oklahoma-state",
    "louisiana-tech",
    "north-carolina-greensboro",
    "southeastern-louisiana",
    "northwestern",
    "illinois",
    "rutgers",
    "nebraska",
    "radford",
    "loyola-il",
    "marshall",
    "mount-st-marys",
    "delaware",
    "oregon-state",
    "southern-illinois",
    "butler",
    "central-arkansas",
    "troy",
    "virginia-military-institute",
    "central-connecticut-state",
    "penn-state",
    "saint-francis-pa",
    "ball-state",
    "njit",
    "north-alabama",
    "north-florida",
    "jacksonville",
    "florida-gulf-coast",
    "alabama-state",
    "georgetown",
    "navy",
    "kent-state",
    "texas-am",
    "arkansas",
    "vanderbilt",
    "south-carolina",
    "brigham-young",
    "wright-state",
    "alcorn-state",
    "long-beach-state",
    "georgia-southern",
    "grambling",
    "alabama",
    "cal-state-fullerton",
    "florida-atlantic",
    "richmond",
    "st-bonaventure",
    "george-washington",
    "duquesne",
    "rhode-island",
    "dayton",
    "fordham",
    "rider",
    "college-of-charleston",
    "texas",
    "hofstra",
    "hampton",
    "miami-fl",
    "north-carolina-state",
    "boston-college",
    "notre-dame",
    "georgia-tech",
    "pittsburgh",
    "wake-forest",
    "princeton",
    "hartford",
    "stetson",
    "indiana",
    "san-diego-state",
    "eastern-michigan",
    "army",
    "southern-methodist",
    "tulsa",
    "connecticut",
    "tulane",
    "memphis",
    "pennsylvania",
    "east-carolina",
    "south-florida",
    "wichita-state",
    "drexel",
    "davidson",
    "massachusetts",
    "saint-josephs",
    "missouri",
    "california",
    "loyola-md",
    "georgia",
    "detroit-mercy",
    "la-salle",
    "southern-illinois-edwardsville",
    "eastern-illinois",
    "tennessee-martin",
    "southeast-missouri-state",
    "austin-peay",
    "tennessee-state",
    "eastern-kentucky",
    "morehead-state",
    "tennessee-tech",
    "jacksonville-state",
    "western-kentucky",
    "ucla",
    "green-bay",
    "samford",
    "kennesaw-state",
    "lipscomb",
    "middle-tennessee",
    "illinois-state",
    "oral-roberts",
    "south-dakota-state",
    "north-dakota",
    "denver",
    "western-illinois",
    "south-dakota",
    "missouri-state",
    "eastern-washington",
    "drake",
    "east-tennessee-state",
    "towson",
    "incarnate-word",
    "miami-oh",
    "california-santa-barbara",
    "south-carolina-state",
    "howard",
    "norfolk-state",
    "florida-am",
    "savannah-state",
    "north-carolina-at",
    "morgan-state",
    "coppin-state",
    "delaware-state",
    "maryland-eastern-shore",
    "bethune-cookman",
    "coastal-carolina",
    "appalachian-state",
    "mcneese-state",
    "southern",
    "nicholls-state",
    "george-mason",
    "bowling-green-state",
    "clemson",
    "saint-marys-ca",
    "california-irvine",
    "st-johns-ny",
    "abilene-christian",
    "kentucky",
    "seton-hall",
    "wofford",
    "georgia-state",
    "houston",
    "ohio-state",
    "iowa-state",
    "northeastern",
    "kansas",
    "new-mexico-state",
    "auburn",
    "washington",
    "utah-state",
    "iona",
    "north-carolina",
    "colgate",
    "tennessee",
    "iowa",
    "cincinnati",
    "old-dominion",
    "purdue",
    "villanova",
    "kansas-state",
    "oregon",
    "wisconsin",
    "oklahoma",
    "mississippi",
    "gardner-webb",
    "virginia",
    "montana",
    "michigan",
    "florida",
    "nevada",
    "northern-kentucky",
    "texas-tech",
    "buffalo",
    "vermont",
    "florida-state",
    "murray-state",
    "marquette",
    "baylor",
    "syracuse",
    "gonzaga",
    "arizona-state",
    "prairie-view",
    "fairleigh-dickinson",
    "bradley",
    "michigan-state",
    "minnesota",
    "louisville",
    "yale",
    "louisiana-state",
    "maryland",
    "saint-louis",
    "virginia-tech",
    "liberty",
    "mississippi-state",
    "central-florida",
    "virginia-commonwealth",
    "duke",
    "temple",
    "belmont",
    "north-dakota-state",
    "north-carolina-central",
]

# Maps opponent names whose cleaned names are not correct
OPPONENT_MAP = {
    "purdue-fort-wayne": "ipfw",
    "little-rock": "arkansas-little-rock",
    "omaha": "nebraska-omaha",
    "st-johns": "st-johns-ny",
    "st-marys": "saint-marys-ca",
    "university-of-california": "california",
    "uc-irvine": "california-irvine",
    "uc-merced": "california-merced",
    "uc-davis": "california-davis",
    "uc-santa-cruz": "california-santa-cruz",
    "uc-riverside": "california-riverside",
    "uc-santa-barbara": "california-santa-barbara",
    "southeastern": "southeastern-louisiana",
    "louisiana": "louisiana-lafayette",
    "texas-rio-grande-valley": "texas-pan-american",
    "point-university": "point",
    "bethesda-university-ca": "bethesda-ca",
    "penn-st-brandywine": "penn-state-brandywine",
    "bob-jones-university": "bob-jones",
    "southeastern-oklahoma-state": "southeastern-oklahoma",
    "southeastern-baptist-college": "se-baptist",
    "missouri-baptist-university": "missouri-baptist",
    "penn-st-wilkes-barre": "penn-state-wilkes-barre",
    "florida-national-university": "florida-national"
}
